# Generated by Django 5.2.8 on 2025-12-16 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='ФИО')),
                ('specialty', models.CharField(max_length=100, verbose_name='Специальность')),
                ('clinic', models.CharField(max_length=200, verbose_name='Клиника')),
                ('rating', models.IntegerField(default=5, verbose_name='Рейтинг')),
                ('review', models.TextField(verbose_name='Отзыв')),
                ('reviewer', models.CharField(max_length=100, verbose_name='Автор отзыва')),
            ],
            options={
                'verbose_name': 'Врач',
                'verbose_name_plural': 'Врачи',
            },
        ),
    ]
